on:
  release:
    types: [published]

env:
  MODRINTH_ID: "XXXXXXXX"
  CURSEFORGE_ID: "000000"
  RELEASE_TYPE: "release"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Change Version
        run: sed -i 's/mod_version=*/mod_version=${{ github.event.release.tag_name }}/g' gradle.properties
      - name: Build
        run: ./gradlew clean build
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: "${{ github.event.release.tag_name }} - ${{ github.event.release. name }}"
          version: "${{ github.event.release.tag_name }}"
          version-type: "release"
          changelog: "${{ github.event.release.body }}"
          java: |
            17          

          github-tag: "${{ github.event.release.tag_name }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

#          curseforge-id: "${{ env.CURSEFORGE_ID }}"
#          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"
#          curseforge-version-type: "${{ steps.get-release.outputs.release-type }}"

#          modrinth-id: "${{ env.MODRINTH_ID }}"
#          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
#          modrinth-version-type: "${{ steps.get-release.outputs.release-type }}"
