on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Validate Gradle
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Build
        run: ./gradlew clean build
      - name: Capture Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
